### ISSUE TITLE
ATI HDMI audio not working

### ISSUE THREAD

**Issue by aboutafter** [libretro/Lakka#292] opened 2016-01-25 23:48 UTC
I think I can't reopen this issue: https://github.com/libretro/Lakka/issues/237

So I'll open a new one. I hope I'm not doing it wrong. Feel free to reopen that thread and close this if it's needed. 

The thing is that  radeon.audio=1 doesn't fix the issue for me. I changed audio_device="hdmi:CARD=HDMI,DEV=0" (the name aplay -L shows for my ATI card) and I don't have sound. 

This is in a PC with an AMD 5770.

**Comment by Kivutar** [comment] 2016-01-26 04:45
You did right.

Let keep the radeon.audio=1 even if it doesn't solve the problem, it will certainly fail without it.

After searching on google, I found that you must have radeon.audio=1, then reboot, and try every item returned by aplay -L.

Have you tried them all?

Don't forget to stop the retroarch service when you test that.

**Comment by aboutafter** [comment] 2016-01-26 11:20
This is going to sound very noobish, but how do I save the radeon.audio=1 line from the cmdline?

**Comment by Kivutar** [comment] 2016-01-26 15:57
Ah, this is documented here https://github.com/libretro/Lakka/wiki/PC
You have to remount the first partition, and edit the bootloader configuration.

**Comment by aboutafter** [comment] 2016-01-27 12:19
There is no extlinux.conf. I made the change in syslinux.conf, but if I press "tab" in the bootloader I don't see the radeon.audio=1 change in the line, so maybe it's not /flash/syslinux.conf the file that needed to be changed.

**Comment by Kivutar** [comment] 2016-01-27 12:52
If you see syslinux.conf, it means you are in live USB mode. /flash/syslinux.conf should be ok. I don't get why the changes are not saved.

Anyway, during the test phase, you can just add radeon.audio=1 manually, and try all the entries returned by aplay -L.

**Comment by aboutafter** [comment] 2016-01-27 16:24
Either way, the sound doesn't work no :(

**Comment by albanibr** [comment] 2016-01-29 18:41
I am also in trouble ...

My audio card is Nvidia...HDMI audio works, but to shutdown the system, have to modify the 48000 Hz Audio to 44100Hz or 44100Hz to 4800HZ. When it works randomly is muted for a few seconds.

ZOTAC GF9300-I-E LGA 775 NVIDIA GeForce 9300 HDMI Mini ITX Intel Motherboard and lakka 64bits

Any solution?

**Comment by Kivutar** [comment] 2016-01-30 02:48
What? You have to change the audio settings to shutdown the system???

**Comment by albanibr** [comment] 2016-01-30 11:40
Sorry for my poor english... :(

lets go!
my audio card is Nvidia HDMI. 

I setup the file .config/retroarch/retroarch.cfg (ssh), and ok! SOUND!
BUT, to restart or shut down the PC, NO SOUND!
There is nothing to do, then modify the audio output rate to 48Khz or 44.1kHz, and works!

Every restart or shutdown, have to modify the audio output rate, and when it works is muted randomly for a few seconds while running some ROM.

im using lakka-Generic.x86_64-devel-20160128074055-r21301-g6429dc7 (online update)

thank you for your attention!

**Comment by Kivutar** [comment] 2016-01-30 12:03
Looks like you forget to stop the retroarch service before editing the retroarch.cfg. Have you read the documentation about that?

**Comment by albanibr** [comment] 2016-01-30 12:12
Follow the instructions in the forum.
And repeat, to change the frequency of audio.

Load putty
root 
root
systemctl stop retroarch
nano .config/retroarch/retroarch.cfg
ctrl w > audio_device
then enter your card inside the quotes
ctrl x > Y > press enter
systemctl start retroarch

I tested other systems on the PC and audio HDMI is working properly, problems with the sound in the lakka!

**Comment by sonikokaruto** [comment] 2016-02-09 06:59
I am having the same problem, i have a foxconn nt-a3500, it has the amd e350, and audioworks with the system speaker (full blast volume), headphones and digital, but it doesn't work with hdmi. I've tried both the 64 and 32 bit versions, both with and without the radeon.audio=1 setting on the extlinux.conf

I don;t know what else to do. 

The thing that kinda stings, is that, openelec with kodi, actually works flawless, but this is not working at all.


I need help :(

**Comment by Kivutar** [comment] 2016-02-10 03:19
Could help: http://unix.stackexchange.com/questions/62683/sound-not-working-when-both-the-sound-card-and-hdmi-use-the-intel-hda-driver-ho

You can also try to use some command line utilities to play audio from the CLI. Like aplay or speaker-test.

**Comment by sonikokaruto** [comment] 2016-02-10 17:28
Oooh, that seems like a good option, i'm gonna try it as soon as i get home
today :)

**Comment by fohoizey** [comment] 2016-02-21 22:35
Hi

Same issue here.
AMD Radeon HD7970
No sound even with radeon.audio=1 and even after having tryed all audio_device settings.

Any idea ?

Thanks

**Comment by sonikokaruto** [comment] 2016-02-21 23:06
Well, i haven't found the time to try the solution about it detecting them in different order, but you could try that. 

Or maybe the team could contact the persons on charge of Kodi-OpenElec to see the way they implemented it.

It would make this a lot more compatible for everyone.

**Comment by Kivutar** [comment] 2016-02-22 04:57
OpenELEC is using X while we are using DRM/KMS.

**Comment by sonikokaruto** [comment] 2016-02-22 17:19
Is thjere a way to change lakka to use X?

**Comment by fohoizey** [comment] 2016-02-22 18:31
If not, is there any solution to get Sound working ? 
There must be a huge amount of people concerned by this bug as it seems to affect all ATI powered PCs
Is there anything we can do to help you debug?

**Comment by sonikokaruto** [comment] 2016-02-22 18:57
Yeah, i'm all for helping, this issue is really bothering me, because these
inexpensive pc's have the muscle and speed to run a lot of stuff smoothly
and with a lot more options than something on, let's say, a raspberry pi

**Comment by fohoizey** [comment] 2016-02-22 20:42
More informations here http://libretro.com/forums/showthread.php?t=5135

**Comment by Kivutar** [comment] 2016-02-23 04:39
Switching to X is easy, but it have to be done at build time. When I provide X images, users who prefer DRM/KMS will complain. When I provide DRM/KMS images, users who prefer X will complain. And I can't (and don't want to) provide both.

I'm in favor to DRM/KMS because it is the future of display on linux, and it has less overhead. Also, it allows us to avoid providing an extra image for nvidia-legacy.

I still want to support PCs, because we're the only distro to support it so far, vs recalbox and retropie. But our PC builds require a lot (too much) of maintainance. I mean compared to an Odroid-XU4, which cost only $70 and will perform as well as a NUC.

**Comment by fohoizey** [comment] 2016-02-23 06:24
I perfectly understand this but there are some people trying to use lakka on much more powerful machines. I'm using a quad core i5 with a powerful gpu, a lot of ram and an ssd. It's a perfect hardware for modern gaming machines' emulation. Dreamcast, PSP, etc. 

Can we (I mean, users like me) build lakka using x easily? Of course I would much prefer finding a solution for the KMS build... 

Anyway, except this point, lakka is perfect on pc

**Comment by sonikokaruto** [comment] 2016-02-23 06:27
Well, thanks for your help.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.1.25&pv=5.0.2&source=email_footer_2] On Mon, Feb 22, 2016 at 10:24 PM, fohoizey < notifications@github.com [notifications@github.com] > wrote:
I perfectly understand this but there are some people trying to use lakka on
much more powerful machines. I'm using a quad core i5 with a powerful gpu, a lot
of ram and an ssd. It's a perfect hardware for modern gaming machines'
emulation. Dreamcast, PSP, etc.

Can we (I mean, users like me) build lakka using x easily? Of course I would
much prefer finding a solution for the KMS build...

Anyway, except this point, lakka is perfect on pc

—
Reply to this email directly or view it on GitHub
[https://github.com/libretro/Lakka/issues/292#issuecomment-187564995] .[https://github.com/notifications/beacon/AGj4xksjTIAzWTseFI6eRrvJ5rlHHJhQks5pm_KigaJpZM4HMGFj.gif]

**Comment by Kivutar** [comment] 2016-02-23 07:02
Yes, reverting that commit https://github.com/libretro/Lakka/commit/48d49cda7fe4db43f9a95e1458ec8f40ed8f3aee and recompiling should do the trick.

**Comment by fohoizey** [comment] 2016-02-23 13:25
I'll try ! Merci
I've just have to download the sources and to compile them ?
I'll let you know if it works. That would be great.

**Comment by Kivutar** [comment] 2016-02-23 14:25
It works, I did it many times ;)
Compilation instructions are on the wiki.

**Comment by fohoizey** [comment] 2016-02-23 19:32
Thanks. I'm using a Mac and it shows error when trying to compile.
Do I have to compile on Linux (which I don't have) ?
Or on the target machine ?

Thanks


fohoizey$ DISTRO=Lakka PROJECT=Generic ARCH=x86_64 make image
./scripts/image mkimage
cat: /proc/cpuinfo: No such file or directory
uname: illegal option -- i
usage: uname [-amnprsv]

 =================================================================================
 Configuration for Lakka (unofficial)
 =================================================================================

 Buildoptions:
 ======================================================
 - CPU (ARCH):				 x86-64 (x86_64)
 - FLOAT:				 
 - FPU:					 
 - SIMD support:			 yes
 - Optimizations:			 size
 - LTO (Link Time Optimization) support: yes
 - GOLD (Google Linker) Support:	 yes
 - LLVM support:			 yes

 Graphic configuration:
 ======================================================
 - Xorg Graphic Drivers:		 r300 r600 radeonsi i915 i965 nvidia
 - XORG Composite support:		 yes
 - WindowManager:			 none
 - SDL support:				 yes
 - OpenGL (GLX) support (provider):	 yes (mesa)
 - OpenGLES support (provider):		 no (no)
 - uvesafb support:			 yes

 Hardware decoder configuration:
 ======================================================
 - Kodi Player driver:			 default
 - VAAPI Support:			 yes
 - VDPAU Support:			 yes

 Input device configuration:
 ======================================================
 - Remote support:			 no
 - ATV Remote support:			 no
 - CEC Adapter support:			 yes
 - IRTrans support:			 no
 - Kodi Joystick support:		 yes

 Misc. hardware configuration:
 ======================================================
 - ALSA support:			 yes
 - Bluetooth support:			 yes
 - LCD drivers:				 irtrans,imon,imonlcd,mdm166a,MtxOrb,lis,dm140,hd44780,CFontz,SureElec,vlsys_m428,serialVFD,shuttleVFD
 - Include driver:			 RTL8192CU
 - Include driver:			 RTL8192DU
 - Include driver:			 RTL8188EU
 - Include driver:			 RTL8812AU
 - Include driver:			 dvbhdhomerun
 - Include firmware:			 misc-firmware
 - Include firmware:			 wlan-firmware
 - Include firmware:			 dvb-firmware
 - Include firmware:			 iwlwifi-firmware

 Network service configuration:
 ======================================================
 - Avahi (Zeroconf) support:		 yes
 - NFS mounting support:		 yes
 - SAMBA mounting support:		 yes
 - SAMBA server support:		 yes
 - SFTP server support:			 yes

 OS configuration:
 ======================================================
 - OEM Support:				 yes
 - Default ROOT Password:		 root
 - Bootloader:				 syslinux
 - UDevil support:			 no
 - Installer support:			 yes

 Misc. Filesystems:
 ======================================================
 - Swap Support:			 no
 - exFAT Support (via Fuse):		 yes
 - NTFS Support (via Fuse):		 yes
 - Install HFS Tools:			 yes

 Kodi configuration:
 ======================================================
 - Kodi version:			 no
 - Kodi nonfree support:		 yes
 - Kodi Blu-Ray support:		 yes
   - Bluray BD+ support:		 yes
   - Bluray AACS support:		 yes
 - Kodi DVDCSS support:			 yes
 - Kodi Airplay support:		 yes
 - Kodi Airtunes support:		 yes
 - Kodi NFS support:			 yes
 - Kodi MySQL support:			 yes
 - Kodi Optical Drive support:		 yes
 - Kodi SAMBA client support:		 yes
 - Kodi SSH client support:		 yes
 - Kodi UPNP support:			 yes
 - Kodi Webserver support:		 yes
 - Include Skin:			 Confluence
 - Default Skin:			 Confluence
 - Include extra fonts:			 yes
 - Include RSXS Screensaver:		 yes
 - Include ProjectM Visualization:	 yes
 - Include Goom Visualization:		 yes

 =================================================================================
 End Configuration for Lakka
 =================================================================================



cat: /proc/cpuinfo: No such file or directory
uname: illegal option -- i
usage: uname [-amnprsv]
**** Your system lacks the following tools needed to build Lakka ****
gawk cvs mkfontscale mkfontdir bdftopcf
********
make: *** [image] Error 1

**Comment by sonikokaruto** [comment] 2016-02-23 20:06
haven't used osx in a while but it seems that you may need to do something like  (and i'm not even sure something like apt-get exists on osx)

sudo apt-get update
sudo apt-get install gawk cvs mkfontscale mkfontdir bdftopcf

**Comment by Kivutar** [comment] 2016-02-24 03:50
I've never tried to compile on OSX. It may work. You need some dependancies like **gawk cvs mkfontscale mkfontdir bdftopcf**. Try to install them using a package mananger like **brew**

**Comment by fohoizey** [comment] 2016-02-24 08:28
Thanks, I've tried to install the dependencies but they nedd others and others and so on.
I'll try on ubuntu at work today.

**Comment by fohoizey** [comment] 2016-02-24 13:08
Argg, unable to compile Lakka because https://www.freedesktop.org (which seems to be called during the compiling process) is down. Any mirror for this domain or any way to fix this ?
Thanks

**Comment by fohoizey** [comment] 2016-02-24 15:28
Damn, it fails somewhere else :


--2016-02-24 16:31:39--  http://sources.openelec.tv/mirror/pcre/pcre-8.36.tar.bz2
Resolving sources.openelec.tv... 82.220.2.33
Connecting to sources.openelec.tv|82.220.2.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-02-24 16:31:39 ERROR 404: Not Found.


Cant't get pcre sources : ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.36.tar.bz2
 Try later !!
make: *** [image] Erreur 1

**Comment by thiscodedbox** [comment] 2016-02-29 17:23
I'm also having the ATI HDMI Audio Problem. Here is my aplay -l and -L

```
card 0: HDMI [HDA ATI HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

hdmi:CARD=HDMI,DEV=0
    HDA ATI HDMI, HDMI 0
    HDMI Audio Output
```

- I disabled the onboard intel audio and video, so the only other driver is null.
- I've added radeon.audio=1 to /flash/extlinux.conf
- I stopped retroarch and added "hdmi:CARD=HDMI,DEV=0" to the audio_device key in .config/retroarch/retroarch.cfg

Oddly enough, via SSH with emulation not running doing a

`aplay -D plughw:0,3 sound.wav`

Seems to play a sound - gives a message it's playing and pauses for the duration of the file - unless I'm running say Super Mario World, then it says the resource is busy. This makes me think it's playing the sound but someone it's not going out the HDMI.

**Comment by Kivutar** [comment] 2016-02-29 17:28
So just set

    audio_device="plughw:0,3"

In your retroarch.cfg. (Without forgetting to stop the retroarch service.)

**Comment by sonikokaruto** [comment] 2016-02-29 17:43
Excuse me, (and ignore my ignorance) but what's the difference between putting 

audio_device="plughw:0,3"

vs

audio_device="hdmi:CARD=HDMI,DEV=0"


Does it handle it differently? (and yeah, i'm gonna try this too)

**Comment by Kivutar** [comment] 2016-02-29 17:50
To be honest I'm not exactly sure. I'd go for "they are synonyms" but only an alsa specialist could reply to that.

**Comment by thiscodedbox** [comment] 2016-03-01 02:57
Thanks Kivutar. I'm sorry - what I typed didn't quite make sense so let me clarify. Below is my output - it's "playing" the sound as far as ALSA is concerned, but there is no sound coming out of my TV which is hooked up to the HDMI:
```
Lakka:~ # aplay -D plughw:0,3 sound.wav
Playing WAVE 'sound.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Stereo
Lakka:~ # speaker-test -c 2 -r 48000 -D hw:0,3

speaker-test 1.0.29

Playback device is hw:0,3
Stream parameters are 48000Hz, S16_LE, 2 channels
Using 16 octaves of pink noise
Rate set to 48000Hz (requested 48000Hz)
Buffer size range from 64 to 16384
Period size range from 32 to 8192
Using max buffer size 16384
Periods = 4
was set period_size = 4096
was set buffer_size = 16384
 0 - Front Left
 1 - Front Right
Time per period = 5.636446
 0 - Front Left
 1 - Front Right
```
`hdmi:CARD=HDMI,DEV=0` or `hw:0,3` for `AUDIO_DEVICE` makes no difference. I feel that retroarch and ALSA is "playing" the audio, but it's just not coming out of the speakers. I'm experimenting with blacklisting drivers via the two confs in /storage/.config/modprobe.d but I'm stabbing in the dark really. An ALSA specialist would be quite handy right about now.

**Comment by sonikokaruto** [comment] 2016-03-01 06:11
I am actually (as of right now) trying this too, and i can tell it's
playing something, just nothing is coming out of my hdmi speakers.

The integrated speaker does work, full volume, but does work.

**Comment by fohoizey** [comment] 2016-03-01 13:54
Hi,

I've finally never been able to compile, it always fail. I face the exact same problems as the others.
Audio seems to be played but ... muted : no sound at all goes to HDMI.
Perhaps it is directed to the internal sound card.

Has anyone been able to compile the "old" X based release that would solve the problem ?

**Comment by sonikokaruto** [comment] 2016-03-01 17:21
I know you have to make a git pull and then compile it, but i haven't been
able to, i know i'm not doing something right, but setting up everything
just to compile lakka, it's getting tiresome and time-wastey, i'm just
thinking of sticking to emulation station on windows and be done with it.

**Comment by Kivutar** [comment] 2016-03-01 19:07
Then why not installing retroarch on windows? It contains the graphical interface of Lakka anyway. So you can set it up exactly the same way.

(An alternative is to invest $40 on an ARM board, and you're done)

**Comment by sonikokaruto** [comment] 2016-03-01 19:21
I was rooting on lakka because it's the only alternative for pc's (just not my spare htpc).

I already have a raspberry pi-2 but wanted to try something like this on pc (with the advantage of having all that extra power so it could run stuff up to dreamcast).

I might as well just go for the odroid-xu4, it seems to be the most capable one.

**Comment by fohoizey** [comment] 2016-03-01 19:43
Well, buying an arm card and being unable to play dreamcast and psp games just because I can't understand how to have sound on lakka don't sound like a good idea to me. 
Lakka is the only retrogaming distribution made for pc and that's why I wanted to use it

**Comment by Kivutar** [comment] 2016-03-01 19:57
Ok, I will build an X11 image when I have some free time during the week.

**Comment by fohoizey** [comment] 2016-03-01 20:00
Merci Jean-André c'est cool :)
Impatient to test it.

**Comment by sonikokaruto** [comment] 2016-03-01 20:04
Thanks, shall try it

**Comment by fohoizey** [comment] 2016-03-02 08:22
Here is where compilation fails :
```
 --2016-03-01 18:58:49--  http://sources.openelec.tv/mirror/pcre/pcre-8.36.tar.bz2
Resolving sources.openelec.tv... 82.220.2.33
Connecting to sources.openelec.tv|82.220.2.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-03-01 18:58:49 ERROR 404: Not Found.


Cant't get pcre sources : ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.36.tar.bz2
 Try later !!
make: *** [image] Erreur 1

```

**Comment by Kivutar** [comment] 2016-03-02 09:18
Replace the version by 3.38 in packages/devel/pcre/package.mk

**Comment by fohoizey** [comment] 2016-03-03 14:16
THanks. Stuck here now :
`checking whether GCC is new enough... no
configure: error:
The selected GCC C++ compiler is not new enough to build LLVM. Please upgrade
to GCC 4.7. You may pass --disable-compiler-version-checks to configure to
bypass these sanity checks.
make: *** [image] Erreur 1
`

**Comment by fohoizey** [comment] 2016-03-08 17:42
I've never been able to compile :( As anyone succeeded ?
I've tried much older releases and still have no -real- sound. I've some strange crackling sound but nothing acceptable.

Should i give up ?

**Comment by Kivutar** [comment] 2016-03-08 18:31
I'm uploading a new version with updated kernel+mesa+libdrm. It **may** fix some of these bugs.

**Comment by thiscodedbox** [comment] 2016-03-08 20:11
Thanks Kivutar - I'll have a look tomorrow. I did A LOT of testing and tweaking with Ubuntu and Debian trying to find a workable situation of running Retroarch on Linux to take advantage of a lean OS and to take advantage of DRM/KMS.

I know running it in X is bad for performance, is it possible that the xorg drivers need to be installed for HDMI audio to work for the ATI cards that have problems? Even though it's running in DRM/KMS, not X, could the drivers still be needed for audio?

I say this because when I was testing with Debian and Ubuntu I had HDMI sound working on Retroarch on Debian and Ubuntu, I found that removing all the xorg stuff and removing the window manager broke HDMI sound - but video was still working - that is DRM/KMS was sort of working - but I ended up changing tack anyway and going with Windows 7 for the time being and for my sanity. I ultimately want the low input lag/latency of Linux though so i'm still in the fight. I'm happy to test anything you send my way and give you feedback. I've found that with the ATI video card the Atom n2800 has been performing even for N64 with a bit of tweaking, and it's dead silent and low power usage.

Intel DN2800MT
2.8ghz Atom n2800
Intel Graphics 3600 (disabled, this is the weird PowerVR chipset that is not really supported)
4GB RAM
250GB Samsung 850 mSATA Boot
ATI HD5430 1GB Graphics PCI-E 1x (full-size PCI-E hooked up with an adapter to the PCI-E slot like this http://ecx.images-amazon.com/images/I/41BVCkOZ4hL._SY355_.jpg)

**Comment by fohoizey** [comment] 2016-03-08 20:21
Many thanks Kivutar ! That sound great ! Where can we download this new version ? I'll give you a feedback immediately.

**Comment by thiscodedbox** [comment] 2016-03-09 03:02
Still having the same ATI problems with the new build. I've gone further in depth, seems to be related to it not getting a valid ELD from the monitor (Samsung TV in my case but happens on other TVs). Seems to be a common problem in Arch and a few other distros running a 4+ Kernel.

```
Lakka:/proc/asound # dmesg|grep HDMI
[    1.219903] [drm]   HDMI-A-1
[   16.252643] snd_hda_codec_hdmi hdaudioC1D0: HDMI ATI/AMD: no speaker allocation for ELD
[   16.260101] input: HDA ATI HDMI HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1c.1/0000:02:00.1/sound/card1/input7
[   16.359448] snd_hda_codec_hdmi hdaudioC1D0: HDMI ATI/AMD: no speaker allocation for ELD
[   16.659783] snd_hda_codec_hdmi hdaudioC1D0: HDMI ATI/AMD: no speaker allocation for ELD
[   16.959301] snd_hda_codec_hdmi hdaudioC1D0: HDMI ATI/AMD: no speaker allocation for ELD
[   17.259257] snd_hda_codec_hdmi hdaudioC1D0: HDMI ATI/AMD: no speaker allocation for ELD

```

**Comment by fohoizey** [comment] 2016-03-09 19:48
No success with the new build :(
The "no speaker allocation for ELD" seems to be a good clue of what's happening.
I've read many topics talking about this and the solution is to manually set allocation using :
xrandr --output HDMI-0 --set audio auto

but xrander is not installed on Lakka.

I'm so sad not being able to use Lakka on my powerful PC :(

**Comment by julianxhokaxhiu** [comment] 2016-03-09 20:20
Sorry to say that but if you really want RetroArch, just install Windows and Retroarch over it, it works fine :) When this will be fixed on Linux kernel and/or driver side, you'll be more than happy to shift to Lakka.

**Comment by sonikokaruto** [comment] 2016-03-09 20:30
Like i said on a previous post, This isn't an issue of the kernel, because other distro that uses openElec as it's base (the media center openElec with kodi) actually works correctly thru hdmi.

I think this is more like kivutar has said: it's an issue between retroarch and the audio driver.

**Comment by Kivutar** [comment] 2016-03-09 20:40
The other OpenELEC derived distros are using X11. We are using DRM/KMS. That makes a big difference. And this difference is in Kernel+Mesa+libdrm+drivers. Not in RetroArch.

**Comment by thiscodedbox** [comment] 2016-03-09 20:44
>  just install Windows and Retroarch over it, it works fine :) When this will be fixed on Linux kernel and/or driver side, you'll be more than happy to shift to Lakka.

Thanks for trying to offer an alternative julianxhokaxhiu but it's already been established that Windows is the easiest route and works fine - it's what I'm doing in the meantime. The better potential for low input lag/latency and for ultimately fewer variables to go wrong (once it's all working) is what draws me to Lakka. I think we should stay on target and troubleshoot this if Kivutar is willing (thanks for all your time)

**Comment by thiscodedbox** [comment] 2016-03-09 20:44
> I think this is more like kivutar has said: it's an issue between retroarch and the audio driver.

I may be out of my element sonikokaruto - but I respectfully disagree - if we're talking about the same issue, something like aplay -D hw:0,3 sound.wav should work - which it *says* it's working, but no sound comes out, probably because of the ELD/EDID issue above. I think it's kernel/driver issues with HDMI itself. Perhaps a different audio driver would fix it just by bypassing all the busted stuff, but I don't think it has anything to do with retroarch itself.

**Comment by fohoizey** [comment] 2016-03-09 20:47
julianxhokaxhiu, that makes sense. 
My PC is in my living room (inside a tv stand). The only device I use to control it is an Xbox 360 wireless game pad, so, having to launch windows and start a software is not really in the same "plug and play" philosophy than lakka... But I perfectly understand the team has not the responsibility of providing me a fully operational and plug and play gaming console, free of charge. 

I think I will have to follow your "advice". 

Thank you Jean-André :)

**Comment by Kivutar** [comment] 2016-03-09 21:05
Well, I still want to fix this bug.

What we know so far, from user reports, and from google searches:

 * this problem happens with the open source radeon driver, not the proprietary one
 * adding radeon.audio=1 in the cmdline fixes it for most people, but not all
 * this problem appeared starting from kernel 3.0, we're using kernel 4.4 now
 * I found no kernel options to force radeon.audio=1

Now, searching that error on google

    no speaker allocation for ELD

led me to this topic, where there are patches https://bugs.freedesktop.org/show_bug.cgi?id=89327

**Comment by sonikokaruto** [comment] 2016-03-09 21:07
Is there a way to (user install) the radeon driver? not sure if openelec is supported

**Comment by Kivutar** [comment] 2016-03-09 21:20
@sonikokaruto What driver are you talking about? The proprietary one? I doubt it is compatible with DRM.

Anyway, none of those patches found on freedesktop or on gentoo can apply, because they are already in the tree most of the time.

Note that this problem affect most linux distros. You can find report of it on almost every distribution tracker by searching "radeon.audio=1" on google. So it will be fixed by an update soon or late.

**Comment by fohoizey** [comment] 2016-03-09 21:38
> Note that this problem affect most linux distros. You can find report of it on almost every distribution tracker by searching "radeon.audio=1" on google. So it will be fixed by an update soon or late.

Yes but it's most of the time solved by changing driver/audio server/forcing the allocation for ELD (xrandr --output HDMI-0 --set audio auto)

**Comment by thiscodedbox** [comment] 2016-03-09 21:49
Yes, I did a cat on eld#0,0 in the proc/asound directory and I saw that it
detects HDMI presence, but doesn't get a valid eld, unplug replug, same
thing, more of the eld errors in dmesg. If we can force an eld manually by
having xrandr in lakka then it might be a great fix. I think radeon.audio =
1 is a red herring and not related to this (other than that in the driver's
aren't perfect)

**Comment by gouchi** [comment] 2016-03-09 23:19
Can you try ?

cat /proc/asound/cards 
** 0** [HDMI           ]: HDA-Intel - HDA Intel HDMI
                      HDA Intel HDMI at 0xf7134000 irq 46
 1 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xf7130000 irq 44

amixer contents -c **0** | grep -A2 HDMI
numid=1,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=**on**
numid=7,iface=CARD,name='HDMI/DP,pcm=7 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off
numid=13,iface=CARD,name='HDMI/DP,pcm=8 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=off

**Comment by Kivutar** [comment] 2016-03-10 11:17
I'm ok to include xrandr if it can help. Will will it function if X is not present?

**Comment by fohoizey** [comment] 2016-03-11 09:15
When you say you are upgrading the audio packages, you mean that it is available in the last nightlybuild ?

**Comment by Kivutar** [comment] 2016-03-11 09:26
Not in this one, but in the next one I will upload, yes.

**Comment by fohoizey** [comment] 2016-03-17 21:38
Hi there, any update ?
When you say Hardware needed, what do you mean ?

**Comment by Kivutar** [comment] 2016-03-18 05:52
Hello @fohoizey 
I've failed to upload the new builds on time due to a regression in retroarch. I will upload again tomorrow or the day after.

When I say hardware needed, I mean that I don't own any ATI hardware allowing me to reproduce this bug at home. So I can't fix it fast.

**Comment by thiscodedbox** [comment] 2016-03-27 07:28
@gouchi - sorry for the delay. here are my results:

```
Lakka:~ # cat /proc/asound/cards
 0 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xd0520000 irq 30
```
```
Lakka:~ # amixer contents -c 0 | grep -A2 HDMI
numid=1,iface=CARD,name='HDMI/DP,pcm=3 Jack'
  ; type=BOOLEAN,access=r-------,values=1
  : values=on
```

Let me know if you have any ideas - it would be great to get this working.

@Kivutar - I Tried the 3/20/16 build - no change on my end.

**Comment by thiscodedbox** [comment] 2016-04-01 23:10
@Kivutar - is it possible to include pulseaudio in Lakka again?

**Comment by Kivutar** [comment] 2016-05-06 14:50
This image have a patch applied that could fix the problem: http://static.kivutar.me/Lakka-Generic.x86_64-devel-20160506163800-r21432-gdd78769.img.gz

Could you try it?

(Sorry but pulseaudio is a no no)

**Comment by thiscodedbox** [comment] 2016-05-07 09:14
@Kivutar - tested and working great with my AMD ATI HD5450 card. Audio is working out of the box without any additional settings other than specify the device in the config - for which entering 'hdmi' works. I had problems with stuttering every 3-6 seconds, butI disabled the chipset and PCI-E power saving features in the BIOS and it fixed the stuttering. Thanks for your work on this!

**Comment by Kivutar** [comment] 2016-05-07 09:17
Great. This patch was found by @gouchi 

@aboutafter could you give it a try too? so I can close the issue.

**Comment by sonikokaruto** [comment] 2016-05-07 18:08
Will try it as soon as i get another storage device (mine blew up in tiny little ssd pieces)

**Comment by mirh** [comment] 2016-05-08 13:56
Does this patch also fix the "no speaker allocation for ELD" errors?

**Comment by Kivutar** [comment] 2016-05-08 20:03
No idea, we don't own ATI cards to check that.

**Comment by thiscodedbox** [comment] 2016-05-09 05:57
> Does this patch also fix the "no speaker allocation for ELD" errors?

Yes @mirh - this does fix that error for me on my HD5450 - let us know if it works for you and what hardware you have. I didn't have to do any configuration other than setting the audio device to "hdmi" in retroarch.cfg.

**Comment by mirh** [comment] 2016-05-09 06:27
:s I was actually more looking forward to have this [mainlined](https://bugzilla.kernel.org/show_bug.cgi?id=85241), rather than just to Lakka per se. 
Could you elaborate better this patch?

**Comment by Kivutar** [comment] 2016-05-09 08:53
This patch have been mainlined, iirc. I backported it. @gouchi could tell you more.

**Comment by gouchi** [comment] 2016-05-09 08:56
This [patch](http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=7403c515c49c033fec33df0814fffdc977e6acdc) which fixed audio hdmi is  available upstream and  it went into 4.6 and the various stable kernel series.

**Comment by fohoizey** [comment] 2016-05-16 10:08
Hi and thanks !

I've tested. Out of the box if i do a:
aplay -D plughw:0,3 sound.wav

I can hear the sound !!! BUT, I have NO sound in games.

How did you get audio working during game ?

Thanks

**Comment by Kivutar** [comment] 2016-05-16 11:27
@fohoizey try to set your Audio Device in the device settings, use left and right to switch. You must restart the games for the setting to take effect.

**Comment by fohoizey** [comment] 2016-05-16 12:49
Thanks. I've tried them all.
aplay -D plughw:0,3 sound.wav plays the sound perfectly if i have launched no games

My audio_device is set to hdmi:CARD=HDMI,DEV=0
When I launch a game, I have strange sounds coming out of the TV (like a very very short and quick repeated noise, that never changes nor stops until I close the game).
On some games I get NO audio during the game but when coming back to Lakka menu (before closing the game) i get this strange quick and repeated noise again.

Same thing with NES or SNES games.

When i change from alsathread to alsa, same thing but sound is different
Switching to OSS totally disable sound.

If I do that :
aplay -D plughw:0,3 sound.wav => i get sound
lauch a game => no sound
aplay -D plughw:0,3 sound.wav => "aplay: main:722: audio open error: Device or resource busy"

Very strange !

**Comment by Kivutar** [comment] 2016-05-16 13:45
You don't have a hdmi:CARD=HDMI,DEV=3 ?

**Comment by fohoizey** [comment] 2016-05-16 13:47
I have tried both 0,0 and 0,3
Nothing seems to be working

**Comment by Kivutar** [comment] 2016-05-16 13:54
Ok, try this

    systemctl stop retroarch
    nano .config/retroarch/retroarch.cfg

Find audio_device, set it to "hw:0,3" and save

    systemctl start retroarch

**Comment by fohoizey** [comment] 2016-05-16 16:47
Thanks

hdmi:CARD=HDMI,DEV=3

and

hw:0,3

have, both, the exact same effect : very short and quick repeated noise on NES games

No sound at all on SNES games

Very strangely, behind this "noise" ... I have low sound on N64 games
No sound at all on Genesis games

Impossible to understand !!

**Comment by fohoizey** [comment] 2016-05-16 17:12
Could it be related to this ?
https://bbs.archlinux.org/viewtopic.php?id=192284

> I fixed the audio using pavucontrol. My HDMI card seemed to have 2 channels with same same name

Good to know too (seen on a forum) :

> The line for a custom audio device should come from "aplay -L" (hdmi:CARD=Nvidia,DEV=0-3). If you end up trying the "plughw:X,Y" or "hw:X,Y" entries, the X and Y values come from "aplay -l".

**Comment by thiscodedbox** [comment] 2016-05-16 22:20
@fohoizey 

Three separate suggestions:

FIRST: Disable any audio controllers (sound cards) in the BIOS (probably a good idea no matter what)

SECOND: Stop Retroarch as @Kivutar suggested above and try this:

`cat /proc/asound/card0/codec#0`

(Adjust if your HDMI is identified as card1 etc.) You'll see lines that looks like (this one is mine for an ATI 5450)

```
Default PCM:
    rates [0x70]: 32000 44100 48000
    bits [0x2]: 16
    formats [0x1]: PCM
```

Based on the rates supported, try changing the `audio_out_rate` in retroarch.cfg from 48000 to 44100 or 32000 (or 96000 or something else if it's supported)

THIRD: Change `audio_latency` in retroarch.cfg to something higher than 32 (say, 64 or 96)

Also you can try and funk with `audio_sync video_hard_sync video_vsync`

**Comment by fohoizey** [comment] 2016-05-18 19:25
Thanks

I've tried all of these solutions.
The only thing that change is that I have _less_ strange sounds over the normal sound in N64 games but it's still a pain to hear
I still get no sound on BG, SNES

I really think it's a bug.
Could it be related to my HDMI cable ? I have no audio nor video problem with openelec

**Comment by sonikokaruto** [comment] 2016-05-18 20:15
Kivutar has stated multiple times that openelec uses another sound system, so if it works correctly on that system, it's not the hardware. I hope.

**Comment by gouchi** [comment] 2016-05-19 10:16
Can you try to get some [log](http://www.lakka.tv/doc/FAQ/#how-do-i-debug-retroarch) to see if there are some errors ?

**Comment by sonikokaruto** [comment] 2016-06-02 03:05
@Kivutar Thank you very much! the version that you uploaded here around a month ago, actually worked on my foxconn nt-a3500!! i only had to set up the audio_device="hdmi:CARD=Generic,DEV=0" and now it works like a charm! thanks!

Now another question: if i update lakka, will i lose this patch?

**Comment by Kivutar** [comment] 2016-06-02 08:27
This patch is included in Lakka now. So it should be OK.

**Closed by Kivutar** 2016-06-02 08:27 UTC
Labels: bug, Hardware Needed
