### ISSUE TITLE
Lakka on Hummingboard i2ex + Wireless xbox controller

### ISSUE THREAD

**Issue by brunski82** [libretro/Lakka#133] opened 2014-10-06 18:29 UTC
Using the Xbox wireless controller with the Microsoft dongle works in the menu and the snex emulator. In the nes and sega emulators, however, the buttons (a,b,x,y, shoulder buttons, and triggers) do nothing. The only buttons that seem to work are select, start, and the d pad.

**Comment by progets** [comment] 2015-01-03 03:40
I think I have the same issue. When I use a real Microsoft wired controller it works on RPi, Cubox-i and i386. When I use a real Microsoft wireless controller with a "knock off" dongle it does show up as a wireless xbox 360 controller but doesn't work by default (on any of the three systems I've tried). If I manually setup the controller it will work but not after a reboot, it needs to be manually configured again. The device shows up as "Bus 002 Device 002: ID 045e:0291 Microsoft Corp. Xbox 360 Wireless Receiver for Windows" when I do a lsusb. Any help that can be provided to either get the wireless controller working automagically or to just get it to save my manual configuration after a reboot would really be helpful. I have seen updates to the xbox 360 wireless config a couple times in the past month and I'm running the Lakka release that came out less than a week ago. Sorry for the long message but I wanted to try to provide as much information as possible. Thanks.

**Comment by Kivutar** [comment] 2015-01-03 10:40
@progets your product_id does not match: 0291 is 657 in decimal, while the configure file here says 654 https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/udev/Xbox_360_Wireless_Receiver.cfg#L4

There are many dongles, and some of them are using different ids. I suggest you use retroarch-joyconfig -a to generate a config for your dongle, and contribute it.

**Comment by progets** [comment] 2015-01-03 19:38
Thanks for your quick response. I have tried that in the past but I'm unclear where this file is built I have tried to search for newly created files and don't find any. I have attached a copy of what I get on the command line using the retroarch-joyconfig -a command. Can you please explain what I need to do with it? Thanks again for your help.
![xbox_wireless_knockoff](https://cloud.githubusercontent.com/assets/9030485/5603503/5e558212-934d-11e4-954b-90ec8e86d12d.jpg)

**Comment by larskj** [comment] 2015-01-21 23:09
I had similar problems getting my Xbox wireless controller to work on my Cuboxi i4pro with a "chinese" receiver dongle. Don't know if any of this helps, but here goes:

I just tried the new built from 21th January where I can see the chinese receiver cfg file has been added. It now detects my controller, but the button layout is all messed up - fx up/down on my controller dpad is menu left/right in lakka.

It turns out all I had to do to get my microsoft xbox 360 controller to work with my chinese receiver was to delete the new chinese cfg file and simply edit the regular 360 cfg file so product_id is instead 657. The button layout on my chinese receiver seems to be exactly the same as what is stated in the regular 360 cfg - are we sure the chinese cfg file has the button layout correct and that it shouldn't simply be the same as the regular 360 cfg file just with different product_id?

Of course the above workaround will cause an official microsoft receiver to stop working so it is not the right way to fix it but it is a temporary solution for me until these things are fixed. A better approach would of course be to delete the chinese cfg and create a new chinese cfg using the regular 360 config file with changed product_id, but I just did it the other quick way to see if it worked.

For those interested, this is how I edited the files on the sdcard of the i4pro: (written by memory, may have minor mistakes)

1. Use putty or similar to connect to device
2. Make new joyconfig folder in /storage
3. edit the joyconfig path in /storage/.config/retroarch/retroarch.cfg to point to /storage/joyconfig
4. Copy the regular (non-chinese) 360 cfg file to /storage/joyconfig along with any other needed cfgs
5. Edit the 360 cfg file in /storage/joyconfig so product_id is set to 657.
6. Reboot device.
7. Have fun playing games with your chinese 360 dongle while waiting for the release. :-)

**Comment by recioalex** [comment] 2015-01-22 08:19
Mmmmm... 

Its the file i use on my X86 machine, in that machine i use xboxdrv version 0.8.5-1

I think the problem is that i use xboxdrv, and lakka uses xpad...

or simply i fucked up the files XD.

i´ll see wath can i do to fix this, i´m on my office and don´t have access to my all my systems, if lakka uses xpad, i´ll upload the Xpad config.

**Comment by Kivutar** [comment] 2015-01-22 11:58
Yes we use the xpad kernel module, and the udev input driver of retroarch.

**Comment by recioalex** [comment] 2015-01-22 20:18
Merged on official retroarch-joyconfig, the modifications of file Xbox_360_Wireless_Receiver_Chinese01.cfg to use original binds, and product id 657. so it will work now on xpad.

**Comment by Kivutar** [comment] 2015-01-22 21:42
Ok, I updated the joypad configs in Lakka, this will be fixed in the next nightly.

**Comment by progets** [comment] 2015-01-23 04:35
larskj - Thanks for the information. I did exactly what you suggested about a week ago to get it to work. I should have updated the post but had forgotten about it. You are also right that if you use the real Microsoft adapter you must change it back or at least swap out the file.

recioalex  and Kivutar  - Thanks for including this dongle in the up coming builds. It's the cheapest one out there as far as I can tell. Microsoft doesn't sell just the dongle (with controller only) so I think there are a lot of people that have XBOX 360 wireless controllers to use but no dongle. This makes a great cheap solution.

**Comment by larskj** [comment] 2015-01-24 11:05
Hi guys, thanks for the quick update. I will verify it on the next nightly when it is available. Great work.

**Closed** 2015-02-06 00:52 UTC
Labels: bug

**Comment by kelmer44** [comment] 2015-02-21 16:04
I have a chinese dongle and have tried it with a Lakka nightly from Feb 6, I can see the chinese cfg file in /etc/retroarch_joypad_autoconfig directory. However when I connect my dongle, it is displayed as Xbox receiver device yet I can't seem to get my controllers in sync with the dongle... This happened as well in Windows when I had the wrong drivers... could this be the case as well?
