### ISSUE TITLE
Browsing through big playlists with screenshots crash RPi3

### ISSUE THREAD

**Issue by killer101** [libretro/Lakka#577] opened 2016-12-16 21:59 UTC
While browsing through big playlists, Lakka crashes after a certain amount of moves and only showing black screenshots after that. Restarting Retroarch solves the problem. This bug is reproducible.

**Comment by gouchi** [comment] 2016-12-17 11:46
Duplicate of #262 which has been reported in [RetroArch issue tracker](https://github.com/libretro/RetroArch/issues/2791).

**Comment by Kivutar** [comment] 2016-12-17 12:17
Yes, I close this one. It affects more platforms than just the RPi

**Closed by Kivutar** 2016-12-17 12:17 UTC
