### ISSUE TITLE
Duplicated content history

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#252] opened 2015-12-13 20:45 UTC
Hi again guys.
The "History tab" inside Lakka is very nice, but on my configuration into the Lakka GUI I see also a tab, with a black square (because no icon is available for it), called "content_history".
It's the same of History tab, and they use the same file: content_history.lpl
There's a way to fix it for use only History tab?
Thx

**Comment by Kivutar** [comment] 2015-12-13 21:43
Hello, this doesn't happen on my setup. Can you remove this content_history.lpl and use only the content_history.rpl located in .config/retroarch?

**Comment by Kivutar** [comment] 2016-01-09 11:31
I think this was due to having two content_history files in your paths. On a fresh install, I can't reproduce this problem. It may affect old systems after an upgrade. But there is nothing we can do to prevent this kind of bugs. I close it for now.

**Closed by Kivutar** 2016-01-09 11:31 UTC
