### ISSUE TITLE
PPSSPP Segfault

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#254] opened 2015-12-15 20:42 UTC
Hi, ppsspp_libretro.so down't work for me.
If I try to launch from shell I see the error Segmentation fault.

**Comment by lollo78** [comment] 2015-12-15 21:13
I forgot to specify that I use a Raspberry Pi 2.

**Comment by Kivutar** [comment] 2015-12-16 00:42
Are you using the latest release? I tested ppsspp on rpi2 myself so it should work.

**Comment by lollo78** [comment] 2015-12-16 09:40
Yes, the latest

**Comment by Kivutar** [comment] 2015-12-24 18:31
Hi @lollo78 
I just tested the latest release with PPSSPP on the RPi2, with the Flow game. And it worked.

**Comment by Kivutar** [comment] 2016-01-04 19:03
You tried with many ROMs? I'm not able to reproduce this bug.

**Comment by lollo78** [comment] 2016-01-15 21:27
I tried with other roms (also in cso format) and I can confirm that PPSSPP works. 
But on Rpi2 it's very very slow (what a pity)

**Comment by Kivutar** [comment] 2016-01-16 07:30
Try to enable all the speed hacks. And choose a light game like FF3. Anyway, we can close this now since it doesn't segfault anymore.

If you want to improve performance, you can declare a bug in PPSSPP libretro repo. Ask them to fix the non buffered rendering. This option is broken, and can improve performance.

**Closed by Kivutar** 2016-01-16 07:30 UTC

**Comment by lollo78** [comment] 2016-01-19 21:07
Ok, Thx. But this feature is broken only for rpi2?

**Comment by Kivutar** [comment] 2016-01-19 21:21
No, it's broken in all platforms for ppsspp-libretro.

**Comment by lollo78** [comment] 2016-01-22 22:32
OK, I opened an issue on the PPSSP libretro core github.
I really hope for a fix.
It could be so nice...
