### ISSUE TITLE
No Video on Pi3

### ISSUE THREAD

**Issue by Madad1996** [libretro/Lakka#352] opened 2016-04-30 18:29 UTC
i just installed the newest .img on my SD and it wont boot.
Red light is on and green light blinks
(raspbian boots just fine with same setup)

**Comment by Kivutar** [comment] 2016-04-30 18:43
Are you sure you downloaded the right image? People often mistake and download the RPi 1 image instead of the RPi 2.

**Comment by Madad1996** [comment] 2016-05-01 06:39
Yes i downloaded the right one (Lakka-RPi2.arm-devel)

**Comment by Kivutar** [comment] 2016-05-01 09:50
Sorry, I have no idea of the cause of the problem then. The RPi2 release have been tested several times on RPi3 this last month.

**Comment by Kivutar** [comment] 2016-05-11 16:36
Sorry, still not able to reproduce, I close this until you get more informations.

**Closed by Kivutar** 2016-05-11 16:36 UTC
