### ISSUE TITLE
Also Retroarch 1.3.2 freeze with multiple scan

### ISSUE THREAD

**Issue by lollo78** [libretro/Lakka#333] opened 2016-03-21 20:36 UTC
With the retroarch binary inside the last Lakka nightly (Lakka-RPi2.arm-devel-20160319231806-r21378-g78af2e1) I tried to scan a lot of roms folder (from No-Intro collection stored on my NAS) at the same time and retroarch Freeze.
To reprocude the bug, start scanning for huge roms collection at the same time: try with Gameboy + Gameboy Advanced + Nintendo 64 + Nintendo + Super Nintendo...
Each of this folder have more than 1000 roms inside. 

EDIT: sometimes the crash occurs also scanning only one folder at a time

**Comment by Kivutar** [comment] 2016-05-11 16:57
This may be fixed now.

**Comment by Kivutar** [comment] 2016-07-30 22:29
Looks like it is fixed.

**Closed by Kivutar** 2016-07-30 22:29 UTC
Labels: bug

**Comment by patriote91** [comment] 2017-06-21 02:02
I was able to reproduce this on the XU4 build of 2.0. My board froze when scanning more than 1000-2000 games. If you need any additional information let me know.
