### ISSUE TITLE
N64 game crash into black screen

### ISSUE THREAD

**Issue by Turimo** [libretro/Lakka#320] opened 2016-03-17 04:11 UTC
Hello,
Its my first Lakka build and i've trouble with the N64 emulator, roms are detected fine but when i start them my screen input turn off
Hope for help 

Also failed exctraction when using Online Update for core and core information

**Comment by Kivutar** [comment] 2016-03-17 14:22
Hello, what hardware are you using, and what exact version of Lakka ?

**Comment by Turimo** [comment] 2016-03-17 15:50
I'm using an old PC with a MSI geforce 8400 gs and Intel Pentium E2140 @ 1.60GHz and 2GB DDR2.I've downloaded the last version on the website (Lakka-Generic.i386-devel-20160206091726-r21311-geaf46ad).

**Comment by Kivutar** [comment] 2016-03-17 18:36
This issue is a duplicate of https://github.com/libretro/Lakka/issues/138

**Closed by Kivutar** 2016-03-17 18:36 UTC
