### ISSUE TITLE
Allwinner A10 hardware acceleration 

### ISSUE THREAD

**Issue by lir448** [libretro/Lakka#316] opened 2016-03-14 08:24 UTC
I use Lakka with Allwinner A10 platform (kind of Mele A1000, 1.2 GHz CPU single core, 512 RAM). PlayStation games run without problems but with reduced resolution, and graphics is poor. Graphics get much better if you enable enhanced resolution, but the emulation speed drops even with the enhanced resolution speedhack and vsync off and threaded video on (because it is a single core processor only).

I know that there is a problem with the driver for the GPU Mali400. Because of this different linux system for this CPU does not have hardware acceleration (except Android projects). Lakka uses the CPU only or the GPU too? And is the hardware acceleration in this case?

**Comment by Kivutar** [comment] 2016-03-14 11:22
Hello @lir448 

Lakka uses:

 * pcsx_rearmed as libretro core, which is software rendered only
 * a 3.4 sunxi kernel
 * sunxi mali blobs
 * GLES 2 to blit the whole image on the screen

There are no libretro-gl cores to emulate playstation so far. So we have to rely on software rendering. Blitting the image using GLES is the best we can do in term of performance.

I don't think that a hardware accelerated core for psx is going to appear soon.

Also, I don't think that a new mali userspace driver will be released for the cubieboard either.

So I guess this will never be fixed. It would require a huge amount of efforts to fix that situation, since the problem is mainly poor software support on Allwinner boards. Our motivation to work on these matter is not going to increase, with the release of new hardwares like the RPis or the Odroids. It would be a bad strategy to spend more time on this, given our limited manpower ressources.

**Closed by Kivutar** 2016-03-14 11:22 UTC
