### ISSUE TITLE
Feature request: manually enter SSID for hidden networks

### ISSUE THREAD

**Issue by autofire372** [libretro/Lakka#540] opened 2016-11-23 01:25 UTC
Currently, Lakka cannot connect to "hidden" wifi networks, period. I would like to be able to manually input the SSID of my home network from the RetroArch GUI, since I don't have admin access on the router to un-hide it.

**Comment by Kivutar** [comment] 2016-12-16 18:39
Duplicate of https://github.com/libretro/Lakka/issues/528

**Closed by Kivutar** 2016-12-16 18:39 UTC
